name: Nightly Build

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - run: bun install

      - name: Build vsix
        run: bash build.sh

      - name: Update Nightly Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete nightly --cleanup-tag -y || true
          gh release create nightly "qol.vsix" \
            --title "Nightly Build" \
            --prerelease
